# @package _global_
# DataAgent专用配置 - 财务数据获取专家
defaults:
  - /model/base@model
  - /tools/akshare_financial_data@toolkits.akshare_data
  - /tools/tabular@toolkits.tabular
  - /agents/workers/standard_agent_config@standard_config
  - _self_

agent:
  name: data_agent
  instructions: |-
    你是专业的财务数据获取专家。使用专用的AKShare工具获取财报数据，不要生成Python代码。

    核心工具：
    - get_financial_reports: 获取完整财务报表（利润表、资产负债表、现金流量表）
    - get_key_metrics_from_reports: 提取关键财务指标（营收、利润、ROE等）
    - get_historical_trend_from_reports: 获取历史趋势数据
    - get_tabular_columns: 分析表格数据结构（用于处理CSV/Excel等文件）
    - get_column_info: 智能解释表格列含义（用于处理CSV/Excel等文件）

    工作流程：
    1. 使用get_financial_reports获取目标公司的完整财务报表数据
    2. 使用get_key_metrics_from_reports提取关键财务指标
    3. 使用get_historical_trend_from_reports获取历史趋势数据
    4. 如果有附加数据文件，使用get_tabular_columns和get_column_info进行分析
    5. 将获取的数据整理成JSON格式，供后续分析使用

    重要提醒：
    - 直接调用工具，不要编写Python代码
    - 确保获取的数据完整准确
    - 保存数据供其他Agent使用

  tool_use_behavior: ${standard_config.standard_behavior.data_collection}

# 专用工具配置
toolkits:
  akshare_data:
    config: ${standard_config.standard_toolkits.akshare_data}
    workspace_root: ${standard_config.standard_workspace.root}

  tabular:
    config: ${standard_config.standard_toolkits.tabular}
    workspace_root: ${standard_config.standard_workspace.root}

# Agent信息配置
agent_info:
  name: "DataAgent"
  role: "财务数据获取专家"
  specialization: "A股财务数据获取、指标提取、数据验证"
  tools:
    - "akshare_financial_data"
    - "tabular"
  capabilities:
    - "获取完整财务报表"
    - "提取关键财务指标"
    - "历史数据分析"
    - "表格数据处理"
  output_format: "JSON格式的财务数据"
  
  # 数据格式标准
  data_format_standards:
    company_info:
      required_fields: ["company_name", "stock_code"]
      optional_fields: ["industry", "market_cap", "listing_date", "description"]
    financial_data:
      required_sections: ["basic_metrics"]
      optional_sections: ["historical_trends", "statements"]
    validation_rules:
      revenue: "number > 0"
      stock_code: "string matching pattern"
      dates: "YYYY-MM-DD format"

# 质量控制
quality_control:
  data_validation: true
  error_handling: "retry_fallback"
  max_retries: 3
  timeout_handling: "graceful_degrade"
  
  # 统一错误处理策略
  error_strategies:
    missing_data:
      basic_metrics: "use_defaults"
      historical_trends: "skip_analysis"
      company_info: "request_user_input"
    invalid_data:
      negative_revenue: "flag_as_error"
      invalid_stock_code: "suggest_correction"
      extreme_values: "validate_and_flag"
    tool_errors:
      timeout: "retry_with_fallback"
      api_failure: "use_cached_data"
      network_error: "queue_for_retry"
  
  # 数据验证规则
  validation_rules:
    completeness_check: true
    consistency_check: true
    range_validation: true
    format_validation: true

# 性能优化
performance:
  enable_caching: true
  cache_duration: 3600
  batch_requests: false
  parallel_processing: false
  
# 数据输出标准
output_standards:
  # 遵循standard_data_formats.yaml中定义的格式
  follow_standard_format: true
  include_metadata: true
  ensure_json_validity: true
  
  # 数据质量要求
  quality_requirements:
    accuracy: "high"
    completeness: "mandatory_fields"
    consistency: "cross_validate"
    timeliness: "latest_available"