# @package _global_
# ReportAgent专用配置 - 专业报告生成专家
defaults:
  - /model/base@model
  - /tools/financial_analysis@toolkits.financial_analyzer
  - /tools/report_saver@toolkits.report_saver
  - /tools/tabular@toolkits.tabular
  - /agents/workers/standard_agent_config@standard_config
  - _self_

agent:
  name: report_agent
  instructions: |-
    你是专业报告生成专家。整合所有前置智能体的分析结果，生成完整、专业的财务分析报告。

    核心任务：
    1. 整合所有前置智能体（DataAgent、DataAnalysisAgent、FinancialAnalysisAgent、ChartGeneratorAgent）的分析结果
    2. 根据分析对象（单公司/多公司）自动调整报告结构
    3. 生成包含所有必要章节的专业报告
    4. 支持MD、HTML、PDF多种格式输出
    5. 确保报告完整、准确、专业

    报告类型识别：
    - 单公司分析：深度财务报告，包含健康评估、趋势分析、投资建议
    - 多公司对比：对比分析报告，包含竞争优势、投资排序

    核心工具：
    - save_analysis_report: 保存分析结果到MD/HTML格式
    - save_pdf_report: 生成PDF格式报告
    - generate_comparison_report: 生成对比分析报告
    - get_tabular_columns: 分析表格数据结构
    - get_column_info: 解释表格列含义

    工作流程：
    1. 收集所有前置智能体的分析结果
    2. 识别分析类型和对象
    3. 选择合适的报告模板
    4. 生成完整报告内容
    5. 保存为多种格式
    6. 验证文件生成成功

    报告结构（单公司）：
    - 执行摘要
    - 公司基本信息
    - 财务分析概览
    - 详细分析（盈利能力、偿债能力、运营效率、成长能力）
    - 趋势分析
    - 行业对比
    - 风险评估
    - 投资建议
    - 未来展望
    - 附录

    报告结构（多公司）：
    - 对比总览
    - 各公司独立分析
    - 对比分析表
    - 投资机会排序
    - 综合建议

    质量要求：
    - 内容完整，无遗漏
    - 数据准确，来源清晰
    - 逻辑清晰，层次分明
    - 专业术语规范
    - 分析深入有价值
    - 格式美观专业
    - 图表配合合理

  tool_use_behavior: ${standard_config.standard_behavior.content_generation}

# 专用工具配置
toolkits:
  financial_analyzer:
    config: ${standard_config.standard_toolkits.financial_analysis}
    workspace_root: ${standard_config.standard_workspace.root}

  report_saver:
    config: ${standard_config.standard_toolkits.report_saver}
    workspace_root: ${standard_config.standard_workspace.root}

  tabular:
    config: ${standard_config.standard_toolkits.tabular}
    workspace_root: ${standard_config.standard_workspace.root}

# Agent信息配置
agent_info:
  name: "ReportAgent"
  role: "专业报告生成专家"
  specialization: "财务报告撰写、数据整合分析、投资建议制定"
  tools:
    - "financial_analysis"
    - "report_saver"
    - "tabular"
  capabilities:
    - "专业财务报告撰写"
    - "多格式报告生成"
    - "数据整合分析"
    - "投资建议制定"
  output_format: "专业财务分析报告（MD/PDF/HTML格式）"
  
  # 数据格式标准
  data_format_standards:
    report_data:
      required_metadata: ["title", "report_type", "company_name", "analysis_date"]
      required_sections: ["executive_summary", "financial_analysis", "investment_recommendation"]
      optional_sections: ["company_overview", "trend_analysis", "risk_assessment", "future_outlook", "appendix"]
    content_validation:
      executive_summary: "concise_overview"
      financial_analysis: "data_driven_insights"
      investment_recommendation: "clear_actionable"
      risk_assessment: "balanced_perspective"
    file_management:
      supported_formats: ["md", "html", "pdf"]
      naming_convention: "structured_and_descriptive"
      location_management: "organized_by_type_and_date"

# 简化的报告配置
report_config:
  # 报告模板设置
  template_settings:
    use_standard_template: true
    include_executive_summary: true
    include_detailed_analysis: true
    include_recommendations: true
    
  # 内容质量要求
  quality_standards: ${standard_config.standard_quality}
  
  # 输出格式设置
  output_formats:
    markdown:
      enabled: true
      file_extension: ".md"
    pdf:
      enabled: true
      file_extension: ".pdf"
    html:
      enabled: true
      file_extension: ".html"
    
  # 文件命名规则
  naming_convention: ${standard_config.standard_naming}
  
  # 报告生成标准
  generation_standards:
    data_integration: "comprehensive"
    analysis_synthesis: "deep_insights"
    recommendation_quality: "specific_and_justified"
    risk_balance: "objective_assessment"
    
# 质量控制
quality_control:
  # 统一错误处理策略
  error_strategies:
    content_generation_errors:
      insufficient_data: "focus_on_available_insights"
      conflicting_analysis: "present_multiple_perspectives"
      missing_charts: "proceed_with_text_analysis"
      unclear_recommendations: "suggest_further_research"
    file_generation_errors:
      pdf_conversion_failure: "fallback_to_html_or_md"
      template_rendering_error: "use_basic_formatting"
      file_save_error: "change_location_or_name"
      formatting_issues: "apply_standard_corrections"
    integration_errors:
      agent_data_missing: "use_partial_data_proceed"
      data_format_mismatch: "convert_to_standard_format"
      chart_reference_errors: "update_or_remove_references"
      metadata_incomplete: "fill_with_available_info"
  
  # 报告质量验证
  validation_rules:
    content_completeness: true
    data_consistency: true
    recommendation_justification: true
    risk_balance_check: true
    format_standards: true
    accessibility_compliance: false

# 性能优化
performance:
  enable_report_cache: true
  cache_duration: 1800
  batch_generation: false
  template_reuse: true
  incremental_updates: true
  
# 输出标准
output_standards:
  # 遵循standard_data_formats.yaml中定义的格式
  follow_standard_format: true
  include_metadata: true
  ensure_json_validity: true
  
  # 报告质量要求
  quality_requirements:
    analytical_depth: "comprehensive"
    professional_quality: "publication_ready"
    actionability: "clear_recommendations"
    data_integrity: "verified_and_sourced"