"""
Instructions for testing Kimi2 model with youtu-agent
"""
print("=" * 60)
print("Kimi2 Model Test Instructions")
print("=" * 60)
print()
print("1. Get your Moonshot API key:")
print("   - Visit https://platform.moonshot.ai/")
print("   - Sign up for an account")
print("   - Find your API key in the account settings")
print()
print("2. Set the API key as an environment variable:")
print("   Windows (Command Prompt):")
print("     set MOONSHOT_API_KEY=your_actual_api_key_here")
print()
print("   Windows (PowerShell):")
print("     $env:MOONSHOT_API_KEY='your_actual_api_key_here'")
print()
print("   Linux/macOS:")
print("     export MOONSHOT_API_KEY=your_actual_api_key_here")
print()
print("3. Run the test:")
print("   python test_kimi2.py")
print()
print("Note: Replace 'your_actual_api_key_here' with your real API key")
print("      from Moonshot AI platform.")
print()
print("If you're getting connection errors, double-check:")
print("- Your API key is correct and active")
print("- You have internet connectivity")
print("- The Moonshot API endpoint is accessible from your location")
print()
print("For youtu-agent configuration:")
print("- The model config is in configs/model/kimi2.yaml")
print("- The agent config is in configs/agents/kimi2_agent.yaml")
print("- You can run the agent with:")
print("  python scripts/cli_chat.py --config_name kimi2_agent --stream")