model_provider:
  type: "chat.completions"
  model: "kimi-k2-0905-preview"
  base_url: "https://api.moonshot.cn/v1"
  api_key: ${oc.env:UTU_LLM_API_KEY}
model_settings:
  temperature: 0.6
  top_p: 0.95