# @package _global_
# 优化版股票分析智能体配置 - 减少token消耗
defaults:
  - /model/base@planner_model
  - /model/base@reporter_model
  - /agents/simple_agents/search_agent@workers.SearchAgent
  - /agents/simple_agents/data_analysis_agent@workers.DataAnalysisAgent
  - /agents/simple_agents/data_analysis_agent@workers.FinancialAnalysisAgent
  - /agents/simple_agents/analysis_agent@workers.ChartGeneratorAgent
  - /agents/simple_agents/analysis_agent@workers.ReportAgent
  - /tools/enhanced_python_executor@toolkits.enhanced_python_executor
  - _self_


type: orchestra

planner_config:
  examples_path: stock_analysis_examples.json
  # 优化：限制计划长度和轨迹历史
  max_trajectory_length: 3
  compress_plan_history: true

# 优化报告器模型配置
reporter_model:
  model_provider:
    type: ${oc.env:UTU_LLM_TYPE}
    model: ${oc.env:UTU_LLM_MODEL}
    api_key: ${oc.env:UTU_LLM_API_KEY}
    base_url: ${oc.env:UTU_LLM_BASE_URL}
  # 优化：减少输出长度
  model_settings:
    max_tokens: 2000

# 优化版Agent指令 - 简化系统提示
workers:
  SearchAgent:
    agent:
      instructions: |-
        你是专业的A股财务数据获取专家。使用AKShare直接获取财务数据，避免搜索。
        
        核心功能：
        - 用ak.stock_lrb_em()获取利润表
        - 用ak.stock_zcfz_em()获取资产负债表  
        - 用ak.stock_xjll_em()获取现金流量表
        - 数据清洗并保存为CSV
        
        优先使用AKShare，失败时再考虑其他方法。
        
  DataAnalysisAgent:
    agent:
      instructions: |-
        财务数据处理专家。专注于数据清洗、统计分析、格式转换。
        处理CSV/Excel数据，计算基础指标，确保数据质量。
        
  FinancialAnalysisAgent:
    agent:
      instructions: |-
        财务分析专家。计算ROE、ROA、负债率等指标，进行趋势分析和同业对比。
        专注于数值计算，避免冗长解释。

# 优化工具配置
toolkits:
  enhanced_python_executor:
    config:
      workspace_root: "./stock_analysis_workspace"
      save_code: true
      timeout: 90  # 减少超时时间
      matplotlib_backend: "Agg"
      # 优化：限制代码输出长度
      max_output_length: 2000
      
      financial_packages:
        - pandas>=1.5.0
        - numpy>=1.21.0
        - matplotlib>=3.5.0
        - seaborn>=0.11.0
        - akshare>=1.12.0
        - plotly>=5.0.0
        - openpyxl>=3.0.0

# 优化工作配置
analysis_settings:
  workdir: "./stock_analysis_workspace"
  save_code: true
  # 优化：限制输出格式
  output_formats: ["html"]  # 只生成HTML，减少重复处理
  chart_formats: ["png"]    # 只生成PNG格式
  
  # 优化：启用数据压缩
  compress_intermediate_results: true
  max_context_length: 8000  # 限制上下文长度

# 优化数据源配置
data_sources:
  akshare:
    enabled: true
    timeout: 20  # 减少超时
    retry_count: 2  # 减少重试次数
    
  # 禁用其他数据源以简化流程
  tushare:
    enabled: false
  yfinance:
    enabled: false

# 优化的Agent配置
workers_info:
  - name: SearchAgent
    desc: A股财务数据获取专家
    strengths: AKShare数据获取、财务报表下载、数据清洗
    weaknesses: 依赖网络连接，API限制
    tools: 
      - enhanced_python_executor
      - bash

  - name: DataAnalysisAgent
    desc: 数据处理专家
    strengths: CSV处理、数据清洗、统计分析
    weaknesses: 仅处理结构化数据
    tools:
      - enhanced_python_executor
      - tabular_data

  - name: FinancialAnalysisAgent
    desc: 财务分析专家
    strengths: 财务比率计算、趋势分析
    weaknesses: 需要干净数据输入
    tools:
      - enhanced_python_executor
      - tabular_data

  - name: ChartGeneratorAgent
    desc: 图表生成专家
    strengths: 财务图表制作、可视化
    weaknesses: 依赖数据质量
    tools:
      - enhanced_python_executor

  - name: ReportAgent
    desc: 报告生成专家
    strengths: HTML报告生成、结果整合
    weaknesses: 依赖前期分析质量
    tools:
      - enhanced_python_executor
      - document

# 优化配置：减少token使用的设置
token_optimization:
  # 减少系统提示长度
  shorten_system_prompts: true
  # 压缩历史消息
  compress_history: true
  # 限制工具输出长度
  limit_tool_output: true
  max_tool_output_length: 1000
  # 启用结果缓存
  enable_caching: true
  # 减少详细解释
  concise_output: true